# Generated by Django 6.0.4 on 2026-04-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('industries_served', models.JSONField(blank=True, default=list)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability', models.CharField(blank=True, help_text='e.g., Part-time, Full-time', max_length=100)),
                ('certifications', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EcosystemPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(choices=[('accelerator', 'Accelerator'), ('incubator', 'Incubator'), ('vc_fund', 'VC Fund'), ('angel_network', 'Angel Network'), ('corporate', 'Corporate Innovation'), ('government', 'Government Body'), ('university', 'University/Research'), ('ngo', 'NGO'), ('other', 'Other')], max_length=50)),
                ('programs_offered', models.JSONField(blank=True, default=list)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('cohort_size', models.PositiveIntegerField(blank=True, null=True)),
                ('equity_taken', models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True)),
                ('funding_provided', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sectors_focus', models.JSONField(blank=True, default=list)),
                ('stage_focus', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InnovatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('areas_of_interest', models.JSONField(blank=True, default=list)),
                ('stage', models.CharField(blank=True, help_text='e.g., Idea, Prototype', max_length=100)),
                ('looking_for', models.JSONField(blank=True, default=list, help_text='e.g., Co-founder, Funding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm_name', models.CharField(blank=True, max_length=200)),
                ('investment_thesis', models.TextField(blank=True)),
                ('sectors_of_interest', models.JSONField(blank=True, default=list)),
                ('investment_stages', models.JSONField(blank=True, default=list)),
                ('ticket_size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ticket_size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('portfolio_companies', models.JSONField(blank=True, default=list)),
                ('total_investments', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(blank=True, help_text='e.g., Pre-seed, Seed, Series A', max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('funding_raised', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('problem_statement', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('target_market', models.TextField(blank=True)),
                ('pitch_deck_url', models.URLField(blank=True)),
                ('looking_for', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
