# Generated by Django 4.2.30 on 2026-04-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('innovator', 'Innovator'), ('startup', 'Startup'), ('investor', 'Investor'), ('consultant', 'Consultant'), ('ecosystem_partner', 'Ecosystem Partner')], default='', max_length=20),
        ),
    ]
