# Generated by Django 6.0.4 on 2026-04-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('startup', 'Startup News'), ('fundraising', 'Fundraising & Investment'), ('ipo', 'IPO & Valuation'), ('venture', 'Venture Capital'), ('industry', 'Industry Updates'), ('national', 'National News'), ('local', 'Local Ecosystem'), ('policy', 'Policy & Regulation'), ('technology', 'Technology'), ('other', 'Other')], default='startup', max_length=30)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsWeeklyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(help_text='e.g., 2025-W17', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
