# Generated by Django 6.0.4 on 2026-04-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('follow_request', 'Follow Request'), ('follow_accepted', 'Follow Accepted'), ('interest_received', 'Interest Received'), ('post_like', 'Post Liked'), ('post_comment', 'Post Commented'), ('new_post', 'New Post')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
